# Generated by Django 6.0 on 2026-01-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_created_dt_review_drink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energydrink',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='energydrink',
            name='taste_profile',
            field=models.TextField(blank=True),
        ),
    ]
