# Generated by Django 6.0.1 on 2026-01-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_energydrink_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydrink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='energy_drinks/'),
        ),
    ]
